# Generated by Django 6.0.7 on 2026-07-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('academic_year', models.CharField(default='2026/2027', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#0A2540', max_length=7)),
                ('secondary_color', models.CharField(default='#C9A227', max_length=7)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'School',
            },
        ),
    ]
